image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - staging
    - production

staging:
    stage: staging
    environment:
        name: staging
        url: https://aqueous-everglades-01943.herokuapp.com/
    when: manual
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    only:
        - staging

production:
    stage: production
    environment:
        name: staging
        url: https://tranquil-plains-83917.herokuapp.com/
    when: manual
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - master
